title: Alison Pedraza
logo: /assets/img/Picture4.jpg
description: Education and Projects 
description: [LinkedIn Profile](www.linkedin.com/in/alison-pedraza)
#show_downloads: true
theme: jekyll-theme-minimal

